#!/bin/sh

UPDATED=$(bash ./_scripts/upgrade_version.sh)

# sleep 1

# Check if there are any changes to commit
# if git diff --cached --quiet; then
if git diff --quiet; then
    echo "There are no changes to commit."
else
    # Commit changes
    git add package.json
    git commit -m "Upgrade API version to $UPDATED" --no-verify
fi