export const continents: Record<string, string> = {
	AF: 'Africa',
	AN: 'Antarctica',
	AS: 'Asia',
	EU: 'Europe',
	NA: 'North America',
	OC: 'Oceania',
	SA: 'South America',
	UN: 'Unknown',
	NAU: 'North America',
	SAU: 'South America',
	AFR: 'Africa',
	ANT: 'Antarctica',
	ASI: 'Asia',
	EUR: 'Europe',
	OCE: 'Oceania',
	ANTARCTICA: 'Antarctica',
	AFRICA: 'Africa',
	ASIA: 'Asia',
	EUROPE: 'Europe',
	'NORTH AMERICA': 'North America',
	'SOUTH AMERICA': 'South America',
	OCEANIA: 'Oceania',
	UNKNOWN: 'Unknown',
};
