interface Country {
  name: string;
  native: string;
  phone: number[];
  continent: string;
  capital: string;
  currency: string[];
  languages: string[];
  continents?: string[]; // Optional, for countries in multiple continents
}

export const countries: Record<string, Country> = {
	AD: {
		name: 'Andorra',
		native: 'Andorra',
		phone: [376],
		continent: 'EU',
		capital: 'Andorra la Vella',
		currency: ['EUR'],
		languages: ['ca'],
	},
	AE: {
		name: 'United Arab Emirates',
		native: 'دولة الإمارات العربية المتحدة',
		phone: [971],
		continent: 'AS',
		capital: 'Abu Dhabi',
		currency: ['AED'],
		languages: ['ara'],
	},
	AF: {
		name: 'Afghanistan',
		native: 'افغانستان',
		phone: [93],
		continent: 'AS',
		capital: 'Kabul',
		currency: ['AFN'],
		languages: ['ps', 'uzb', 'tuk'],
	},
	AG: {
		name: 'Antigua and Barbuda',
		native: 'Antigua and Barbuda',
		phone: [1268],
		continent: 'NA',
		capital: "Saint John's",
		currency: ['XCD'],
		languages: ['eng'],
	},
	AI: {
		name: 'Anguilla',
		native: 'Anguilla',
		phone: [1264],
		continent: 'NA',
		capital: 'The Valley',
		currency: ['XCD'],
		languages: ['eng'],
	},
	AL: {
		name: 'Albania',
		native: 'Shqipëria',
		phone: [355],
		continent: 'EU',
		capital: 'Tirana',
		currency: ['ALL'],
		languages: ['sqi'],
	},
	AM: {
		name: 'Armenia',
		native: 'Հայաստան',
		phone: [374],
		continent: 'AS',
		capital: 'Yerevan',
		currency: ['AMD'],
		languages: ['hy', 'arm', 'rus'],
	},
	AO: {
		name: 'Angola',
		native: 'Angola',
		phone: [244],
		continent: 'AF',
		capital: 'Luanda',
		currency: ['AOA'],
		languages: ['por'],
	},
	AQ: {
		name: 'Antarctica',
		native: 'Antarctica',
		phone: [672],
		continent: 'AN',
		capital: '',
		currency: [],
		languages: [],
	},
	AR: {
		name: 'Argentina',
		native: 'Argentina',
		phone: [54],
		continent: 'SA',
		capital: 'Buenos Aires',
		currency: ['ARS'],
		languages: ['spa', 'grn'],
	},
	AS: {
		name: 'American Samoa',
		native: 'American Samoa',
		phone: [1684],
		continent: 'OC',
		capital: 'Pago Pago',
		currency: ['USD'],
		languages: ['eng', 'smo'],
	},
	AT: {
		name: 'Austria',
		native: 'Österreich',
		phone: [43],
		continent: 'EU',
		capital: 'Vienna',
		currency: ['EUR'],
		languages: ['deu'],
	},
	AU: {
		name: 'Australia',
		native: 'Australia',
		phone: [61],
		continent: 'OC',
		capital: 'Canberra',
		currency: ['AUD'],
		languages: ['eng'],
	},
	AW: {
		name: 'Aruba',
		native: 'Aruba',
		phone: [297],
		continent: 'NA',
		capital: 'Oranjestad',
		currency: ['AWG'],
		languages: ['nld', 'pa'],
	},
	AX: {
		name: 'Aland',
		native: 'Åland',
		phone: [358],
		continent: 'EU',
		capital: 'Mariehamn',
		currency: ['EUR'],
		languages: ['swe'],
	},
	AZ: {
		name: 'Azerbaijan',
		native: 'Azərbaycan',
		phone: [994],
		continent: 'AS',
		continents: ['AS', 'EU'],
		capital: 'Baku',
		currency: ['AZN'],
		languages: ['aze'],
	},
	BA: {
		name: 'Bosnia and Herzegovina',
		native: 'Bosna i Hercegovina',
		phone: [387],
		continent: 'EU',
		capital: 'Sarajevo',
		currency: ['BAM'],
		languages: ['bos', 'hrv', 'srp'],
	},
	BB: {
		name: 'Barbados',
		native: 'Barbados',
		phone: [1246],
		continent: 'NA',
		capital: 'Bridgetown',
		currency: ['BBD'],
		languages: ['eng'],
	},
	BD: {
		name: 'Bangladesh',
		native: 'Bangladesh',
		phone: [880],
		continent: 'AS',
		capital: 'Dhaka',
		currency: ['BDT'],
		languages: ['bn'],
	},
	BE: {
		name: 'Belgium',
		native: 'België',
		phone: [32],
		continent: 'EU',
		capital: 'Brussels',
		currency: ['EUR'],
		languages: ['nld', 'fre', 'deu'],
	},
	BF: {
		name: 'Burkina Faso',
		native: 'Burkina Faso',
		phone: [226],
		continent: 'AF',
		capital: 'Ouagadougou',
		currency: ['XOF'],
		languages: ['fre', 'ff'],
	},
	BG: {
		name: 'Bulgaria',
		native: 'България',
		phone: [359],
		continent: 'EU',
		capital: 'Sofia',
		currency: ['BGN'],
		languages: ['bg'],
	},
	BH: {
		name: 'Bahrain',
		native: '\u200fالبحرين',
		phone: [973],
		continent: 'AS',
		capital: 'Manama',
		currency: ['BHD'],
		languages: ['ara'],
	},
	BI: {
		name: 'Burundi',
		native: 'Burundi',
		phone: [257],
		continent: 'AF',
		capital: 'Bujumbura',
		currency: ['BIF'],
		languages: ['fre', 'rn'],
	},
	BJ: {
		name: 'Benin',
		native: 'Bénin',
		phone: [229],
		continent: 'AF',
		capital: 'Porto-Novo',
		currency: ['XOF'],
		languages: ['fre'],
	},
	BL: {
		name: 'Saint Barthelemy',
		native: 'Saint-Barthélemy',
		phone: [590],
		continent: 'NA',
		capital: 'Gustavia',
		currency: ['EUR'],
		languages: ['fre'],
	},
	BM: {
		name: 'Bermuda',
		native: 'Bermuda',
		phone: [1441],
		continent: 'NA',
		capital: 'Hamilton',
		currency: ['BMD'],
		languages: ['eng'],
	},
	BN: {
		name: 'Brunei',
		native: 'Negara Brunei Darussalam',
		phone: [673],
		continent: 'AS',
		capital: 'Bandar Seri Begawan',
		currency: ['BND'],
		languages: ['msa'],
	},
	BO: {
		name: 'Bolivia',
		native: 'Bolivia',
		phone: [591],
		continent: 'SA',
		capital: 'Sucre',
		currency: ['BOB', 'BOV'],
		languages: ['spa', 'ay', 'qu'],
	},
	BQ: {
		name: 'Bonaire',
		native: 'Bonaire',
		phone: [5997],
		continent: 'NA',
		capital: 'Kralendijk',
		currency: ['USD'],
		languages: ['nld'],
	},
	BR: {
		name: 'Brazil',
		native: 'Brasil',
		phone: [55],
		continent: 'SA',
		capital: 'Brasília',
		currency: ['BRL'],
		languages: ['por'],
	},
	BS: {
		name: 'Bahamas',
		native: 'Bahamas',
		phone: [1242],
		continent: 'NA',
		capital: 'Nassau',
		currency: ['BSD'],
		languages: ['eng'],
	},
	BT: {
		name: 'Bhutan',
		native: 'ʼbrug-yul',
		phone: [975],
		continent: 'AS',
		capital: 'Thimphu',
		currency: ['BTN', 'INR'],
		languages: ['dz'],
	},
	BV: {
		name: 'Bouvet Island',
		native: 'Bouvetøya',
		phone: [47],
		continent: 'AN',
		capital: '',
		currency: ['NOK'],
		languages: ['nor', 'nob', 'nno'],
	},
	BW: {
		name: 'Botswana',
		native: 'Botswana',
		phone: [267],
		continent: 'AF',
		capital: 'Gaborone',
		currency: ['BWP'],
		languages: ['eng', 'tsn'],
	},
	BY: {
		name: 'Belarus',
		native: 'Белару́сь',
		phone: [375],
		continent: 'EU',
		capital: 'Minsk',
		currency: ['BYN'],
		languages: ['bel', 'rus'],
	},
	BZ: {
		name: 'Belize',
		native: 'Belize',
		phone: [501],
		continent: 'NA',
		capital: 'Belmopan',
		currency: ['BZD'],
		languages: ['eng', 'spa'],
	},
	CA: {
		name: 'Canada',
		native: 'Canada',
		phone: [1],
		continent: 'NA',
		capital: 'Ottawa',
		currency: ['CAD'],
		languages: ['eng', 'fre', 'caf'],
	},
	CC: {
		name: 'Cocos (Keeling) Islands',
		native: 'Cocos (Keeling) Islands',
		phone: [61],
		continent: 'AS',
		capital: 'West Island',
		currency: ['AUD'],
		languages: ['eng'],
	},
	CD: {
		name: 'Democratic Republic of the Congo',
		native: 'République démocratique du Congo',
		phone: [243],
		continent: 'AF',
		capital: 'Kinshasa',
		currency: ['CDF'],
		languages: ['fre', 'lin', 'kon', 'swa', 'lub'],
	},
	CF: {
		name: 'Central African Republic',
		native: 'Ködörösêse tî Bêafrîka',
		phone: [236],
		continent: 'AF',
		capital: 'Bangui',
		currency: ['XAF'],
		languages: ['fre', 'sag'],
	},
	CG: {
		name: 'Republic of the Congo',
		native: 'République du Congo',
		phone: [242],
		continent: 'AF',
		capital: 'Brazzaville',
		currency: ['XAF'],
		languages: ['fre', 'lin'],
	},
	CH: {
		name: 'Switzerland',
		native: 'Schweiz',
		phone: [41],
		continent: 'EU',
		capital: 'Bern',
		currency: ['CHE', 'CHF', 'CHW'],
		languages: ['deu', 'fre', 'ita'],
	},
	CI: {
		name: 'Ivory Coast',
		native: "Côte d'Ivoire",
		phone: [225],
		continent: 'AF',
		capital: 'Yamoussoukro',
		currency: ['XOF'],
		languages: ['fre'],
	},
	CK: {
		name: 'Cook Islands',
		native: 'Cook Islands',
		phone: [682],
		continent: 'OC',
		capital: 'Avarua',
		currency: ['NZD'],
		languages: ['eng'],
	},
	CL: {
		name: 'Chile',
		native: 'Chile',
		phone: [56],
		continent: 'SA',
		capital: 'Santiago',
		currency: ['CLF', 'CLP'],
		languages: ['spa'],
	},
	CM: {
		name: 'Cameroon',
		native: 'Cameroon',
		phone: [237],
		continent: 'AF',
		capital: 'Yaoundé',
		currency: ['XAF'],
		languages: ['eng', 'fre'],
	},
	CN: {
		name: 'China',
		native: '中国',
		phone: [86],
		continent: 'AS',
		capital: 'Beijing',
		currency: ['CNY'],
		languages: ['man', 'yue', 'can', 'wuu', 'jin', 'hak', 'zh'],
	},
	CO: {
		name: 'Colombia',
		native: 'Colombia',
		phone: [57],
		continent: 'SA',
		capital: 'Bogotá',
		currency: ['COP'],
		languages: ['spa'],
	},
	CR: {
		name: 'Costa Rica',
		native: 'Costa Rica',
		phone: [506],
		continent: 'NA',
		capital: 'San José',
		currency: ['CRC'],
		languages: ['spa'],
	},
	CU: {
		name: 'Cuba',
		native: 'Cuba',
		phone: [53],
		continent: 'NA',
		capital: 'Havana',
		currency: ['CUC', 'CUP'],
		languages: ['spa'],
	},
	CV: {
		name: 'Cape Verde',
		native: 'Cabo Verde',
		phone: [238],
		continent: 'AF',
		capital: 'Praia',
		currency: ['CVE'],
		languages: ['por'],
	},
	CW: {
		name: 'Curacao',
		native: 'Curaçao',
		phone: [5999],
		continent: 'NA',
		capital: 'Willemstad',
		currency: ['ANG'],
		languages: ['nld', 'pa', 'eng'],
	},
	CX: {
		name: 'Christmas Island',
		native: 'Christmas Island',
		phone: [61],
		continent: 'AS',
		capital: 'Flying Fish Cove',
		currency: ['AUD'],
		languages: ['eng'],
	},
	CY: {
		name: 'Cyprus',
		native: 'Κύπρος',
		phone: [357],
		continent: 'EU',
		capital: 'Nicosia',
		currency: ['EUR'],
		languages: ['gre', 'tur', 'hy', 'arm'],
	},
	CZ: {
		name: 'Czech Republic',
		native: 'Česká republika',
		phone: [420],
		continent: 'EU',
		capital: 'Prague',
		currency: ['CZK'],
		languages: ['cs'],
	},
	DE: {
		name: 'Germany',
		native: 'Deutschland',
		phone: [49],
		continent: 'EU',
		capital: 'Berlin',
		currency: ['EUR'],
		languages: ['deu'],
	},
	DJ: {
		name: 'Djibouti',
		native: 'Djibouti',
		phone: [253],
		continent: 'AF',
		capital: 'Djibouti',
		currency: ['DJF'],
		languages: ['fre', 'ara'],
	},
	DK: {
		name: 'Denmark',
		native: 'Danmark',
		phone: [45],
		continent: 'EU',
		continents: ['EU', 'NA'],
		capital: 'Copenhagen',
		currency: ['DKK'],
		languages: ['dan'],
	},
	DM: {
		name: 'Dominica',
		native: 'Dominica',
		phone: [1767],
		continent: 'NA',
		capital: 'Roseau',
		currency: ['XCD'],
		languages: ['eng'],
	},
	DO: {
		name: 'Dominican Republic',
		native: 'República Dominicana',
		phone: [1809, 1829, 1849],
		continent: 'NA',
		capital: 'Santo Domingo',
		currency: ['DOP'],
		languages: ['spa'],
	},
	DZ: {
		name: 'Algeria',
		native: 'الجزائر',
		phone: [213],
		continent: 'AF',
		capital: 'Algiers',
		currency: ['DZD'],
		languages: ['ara'],
	},
	EC: {
		name: 'Ecuador',
		native: 'Ecuador',
		phone: [593],
		continent: 'SA',
		capital: 'Quito',
		currency: ['USD'],
		languages: ['spa'],
	},
	EE: {
		name: 'Estonia',
		native: 'Eesti',
		phone: [372],
		continent: 'EU',
		capital: 'Tallinn',
		currency: ['EUR'],
		languages: ['est'],
	},
	EG: {
		name: 'Egypt',
		native: 'مصر\u200e',
		phone: [20],
		continent: 'AF',
		continents: ['AF', 'AS'],
		capital: 'Cairo',
		currency: ['EGP'],
		languages: ['ara'],
	},
	EH: {
		name: 'Western Sahara',
		native: 'الصحراء الغربية',
		phone: [212],
		continent: 'AF',
		capital: 'El Aaiún',
		currency: ['MAD', 'DZD', 'MRU'],
		languages: ['spa'],
	},
	ER: {
		name: 'Eritrea',
		native: 'ኤርትራ',
		phone: [291],
		continent: 'AF',
		capital: 'Asmara',
		currency: ['ERN'],
		languages: ['ti', 'ara', 'eng'],
	},
	ES: {
		name: 'Spain',
		native: 'España',
		phone: [34],
		continent: 'EU',
		capital: 'Madrid',
		currency: ['EUR'],
		languages: ['spa', 'eu', 'ca', 'gl', 'oc'],
	},
	ET: {
		name: 'Ethiopia',
		native: 'ኢትዮጵያ',
		phone: [251],
		continent: 'AF',
		capital: 'Addis Ababa',
		currency: ['ETB'],
		languages: ['amh'],
	},
	FI: {
		name: 'Finland',
		native: 'Suomi',
		phone: [358],
		continent: 'EU',
		capital: 'Helsinki',
		currency: ['EUR'],
		languages: ['fin', 'swe'],
	},
	FJ: {
		name: 'Fiji',
		native: 'Fiji',
		phone: [679],
		continent: 'OC',
		capital: 'Suva',
		currency: ['FJD'],
		languages: ['eng', 'fij', 'hin', 'urd'],
	},
	FK: {
		name: 'Falkland Islands',
		native: 'Falkland Islands',
		phone: [500],
		continent: 'SA',
		capital: 'Stanley',
		currency: ['FKP'],
		languages: ['eng'],
	},
	FM: {
		name: 'Micronesia',
		native: 'Micronesia',
		phone: [691],
		continent: 'OC',
		capital: 'Palikir',
		currency: ['USD'],
		languages: ['eng'],
	},
	FO: {
		name: 'Faroe Islands',
		native: 'Føroyar',
		phone: [298],
		continent: 'EU',
		capital: 'Tórshavn',
		currency: ['DKK'],
		languages: ['fao'],
	},
	FR: {
		name: 'France',
		native: 'France',
		phone: [33],
		continent: 'EU',
		capital: 'Paris',
		currency: ['EUR'],
		languages: ['fre'],
	},
	GA: {
		name: 'Gabon',
		native: 'Gabon',
		phone: [241],
		continent: 'AF',
		capital: 'Libreville',
		currency: ['XAF'],
		languages: ['fre'],
	},
	GB: {
		name: 'United Kingdom',
		native: 'United Kingdom',
		phone: [44],
		continent: 'EU',
		capital: 'London',
		currency: ['GBP'],
		languages: ['eng'],
	},
	GD: {
		name: 'Grenada',
		native: 'Grenada',
		phone: [1473],
		continent: 'NA',
		capital: "St. George's",
		currency: ['XCD'],
		languages: ['eng'],
	},
	GE: {
		name: 'Georgia',
		native: 'საქართველო',
		phone: [995],
		continent: 'AS',
		continents: ['AS', 'EU'],
		capital: 'Tbilisi',
		currency: ['GEL'],
		languages: ['geo'],
	},
	GF: {
		name: 'French Guiana',
		native: 'Guyane française',
		phone: [594],
		continent: 'SA',
		capital: 'Cayenne',
		currency: ['EUR'],
		languages: ['fre'],
	},
	GG: {
		name: 'Guernsey',
		native: 'Guernsey',
		phone: [44],
		continent: 'EU',
		capital: 'St. Peter Port',
		currency: ['GBP'],
		languages: ['eng', 'fre'],
	},
	GH: {
		name: 'Ghana',
		native: 'Ghana',
		phone: [233],
		continent: 'AF',
		capital: 'Accra',
		currency: ['GHS'],
		languages: ['eng'],
	},
	GI: {
		name: 'Gibraltar',
		native: 'Gibraltar',
		phone: [350],
		continent: 'EU',
		capital: 'Gibraltar',
		currency: ['GIP'],
		languages: ['eng'],
	},
	GL: {
		name: 'Greenland',
		native: 'Kalaallit Nunaat',
		phone: [299],
		continent: 'NA',
		capital: 'Nuuk',
		currency: ['DKK'],
		languages: ['kl'],
	},
	GM: {
		name: 'Gambia',
		native: 'Gambia',
		phone: [220],
		continent: 'AF',
		capital: 'Banjul',
		currency: ['GMD'],
		languages: ['eng'],
	},
	GN: {
		name: 'Guinea',
		native: 'Guinée',
		phone: [224],
		continent: 'AF',
		capital: 'Conakry',
		currency: ['GNF'],
		languages: ['fre', 'ff'],
	},
	GP: {
		name: 'Guadeloupe',
		native: 'Guadeloupe',
		phone: [590],
		continent: 'NA',
		capital: 'Basse-Terre',
		currency: ['EUR'],
		languages: ['fre'],
	},
	GQ: {
		name: 'Equatorial Guinea',
		native: 'Guinea Ecuatorial',
		phone: [240],
		continent: 'AF',
		capital: 'Malabo',
		currency: ['XAF'],
		languages: ['spa', 'fre'],
	},
	GR: {
		name: 'Greece',
		native: 'Ελλάδα',
		phone: [30],
		continent: 'EU',
		capital: 'Athens',
		currency: ['EUR'],
		languages: ['gre'],
	},
	GS: {
		name: 'South Georgia and the South Sandwich Islands',
		native: 'South Georgia',
		phone: [500],
		continent: 'AN',
		capital: 'King Edward Point',
		currency: ['GBP'],
		languages: ['eng'],
	},
	GT: {
		name: 'Guatemala',
		native: 'Guatemala',
		phone: [502],
		continent: 'NA',
		capital: 'Guatemala City',
		currency: ['GTQ'],
		languages: ['spa'],
	},
	GU: {
		name: 'Guam',
		native: 'Guam',
		phone: [1671],
		continent: 'OC',
		capital: 'Hagåtña',
		currency: ['USD'],
		languages: ['eng', 'cha', 'spa'],
	},
	GW: {
		name: 'Guinea-Bissau',
		native: 'Guiné-Bissau',
		phone: [245],
		continent: 'AF',
		capital: 'Bissau',
		currency: ['XOF'],
		languages: ['por'],
	},
	GY: {
		name: 'Guyana',
		native: 'Guyana',
		phone: [592],
		continent: 'SA',
		capital: 'Georgetown',
		currency: ['GYD'],
		languages: ['eng'],
	},
	HK: {
		name: 'Hong Kong',
		native: '香港',
		phone: [852],
		continent: 'AS',
		capital: 'City of Victoria',
		currency: ['HKD'],
		languages: ['man', 'eng'],
	},
	HM: {
		name: 'Heard Island and McDonald Islands',
		native: 'Heard Island and McDonald Islands',
		phone: [61],
		continent: 'AN',
		capital: '',
		currency: ['AUD'],
		languages: ['eng'],
	},
	HN: {
		name: 'Honduras',
		native: 'Honduras',
		phone: [504],
		continent: 'NA',
		capital: 'Tegucigalpa',
		currency: ['HNL'],
		languages: ['spa'],
	},
	HR: {
		name: 'Croatia',
		native: 'Hrvatska',
		phone: [385],
		continent: 'EU',
		capital: 'Zagreb',
		currency: ['EUR'],
		languages: ['hrv'],
	},
	HT: {
		name: 'Haiti',
		native: 'Haïti',
		phone: [509],
		continent: 'NA',
		capital: 'Port-au-Prince',
		currency: ['HTG', 'USD'],
		languages: ['fre', 'ht'],
	},
	HU: {
		name: 'Hungary',
		native: 'Magyarország',
		phone: [36],
		continent: 'EU',
		capital: 'Budapest',
		currency: ['HUF'],
		languages: ['hu'],
	},
	ID: {
		name: 'Indonesia',
		native: 'Indonesia',
		phone: [62],
		continent: 'AS',
		capital: 'Jakarta',
		currency: ['IDR'],
		languages: ['id'],
	},
	IE: {
		name: 'Ireland',
		native: 'Éire',
		phone: [353],
		continent: 'EU',
		capital: 'Dublin',
		currency: ['EUR'],
		languages: ['ga', 'eng'],
	},
	IL: {
		name: 'Israel',
		native: 'יִשְׂרָאֵל',
		phone: [972],
		continent: 'AS',
		capital: 'Jerusalem',
		currency: ['ILS'],
		languages: ['heb', 'ara'],
	},
	IM: {
		name: 'Isle of Man',
		native: 'Isle of Man',
		phone: [44],
		continent: 'EU',
		capital: 'Douglas',
		currency: ['GBP'],
		languages: ['eng', 'glv'],
	},
	IN: {
		name: 'India',
		native: 'भारत',
		phone: [91],
		continent: 'AS',
		capital: 'New Delhi',
		currency: ['INR'],
		languages: ['hin', 'eng'],
	},
	IO: {
		name: 'British Indian Ocean Territory',
		native: 'British Indian Ocean Territory',
		phone: [246],
		continent: 'AS',
		capital: 'Diego Garcia',
		currency: ['USD'],
		languages: ['eng'],
	},
	IQ: {
		name: 'Iraq',
		native: 'العراق',
		phone: [964],
		continent: 'AS',
		capital: 'Baghdad',
		currency: ['IQD'],
		languages: ['ara', 'ku'],
	},
	IR: {
		name: 'Iran',
		native: 'ایران',
		phone: [98],
		continent: 'AS',
		capital: 'Tehran',
		currency: ['IRR'],
		languages: ['fa'],
	},
	IS: {
		name: 'Iceland',
		native: 'Ísland',
		phone: [354],
		continent: 'EU',
		capital: 'Reykjavik',
		currency: ['ISK'],
		languages: ['is'],
	},
	IT: {
		name: 'Italy',
		native: 'Italia',
		phone: [39],
		continent: 'EU',
		capital: 'Rome',
		currency: ['EUR'],
		languages: ['ita'],
	},
	JE: {
		name: 'Jersey',
		native: 'Jersey',
		phone: [44],
		continent: 'EU',
		capital: 'Saint Helier',
		currency: ['GBP'],
		languages: ['eng', 'fre'],
	},
	JM: {
		name: 'Jamaica',
		native: 'Jamaica',
		phone: [1876],
		continent: 'NA',
		capital: 'Kingston',
		currency: ['JMD'],
		languages: ['eng'],
	},
	JO: {
		name: 'Jordan',
		native: 'الأردن',
		phone: [962],
		continent: 'AS',
		capital: 'Amman',
		currency: ['JOD'],
		languages: ['ara'],
	},
	JP: {
		name: 'Japan',
		native: '日本',
		phone: [81],
		continent: 'AS',
		capital: 'Tokyo',
		currency: ['JPY'],
		languages: ['ja'],
	},
	KE: {
		name: 'Kenya',
		native: 'Kenya',
		phone: [254],
		continent: 'AF',
		capital: 'Nairobi',
		currency: ['KES'],
		languages: ['eng', 'swa'],
	},
	KG: {
		name: 'Kyrgyzstan',
		native: 'Кыргызстан',
		phone: [996],
		continent: 'AS',
		capital: 'Bishkek',
		currency: ['KGS'],
		languages: ['ky', 'rus'],
	},
	KH: {
		name: 'Cambodia',
		native: 'Kâmpŭchéa',
		phone: [855],
		continent: 'AS',
		capital: 'Phnom Penh',
		currency: ['KHR'],
		languages: ['cam'],
	},
	KI: {
		name: 'Kiribati',
		native: 'Kiribati',
		phone: [686],
		continent: 'OC',
		capital: 'South Tarawa',
		currency: ['AUD'],
		languages: ['eng'],
	},
	KM: {
		name: 'Comoros',
		native: 'Komori',
		phone: [269],
		continent: 'AF',
		capital: 'Moroni',
		currency: ['KMF'],
		languages: ['ara', 'fre'],
	},
	KN: {
		name: 'Saint Kitts and Nevis',
		native: 'Saint Kitts and Nevis',
		phone: [1869],
		continent: 'NA',
		capital: 'Basseterre',
		currency: ['XCD'],
		languages: ['eng'],
	},
	KP: {
		name: 'North Korea',
		native: '북한',
		phone: [850],
		continent: 'AS',
		capital: 'Pyongyang',
		currency: ['KPW'],
		languages: ['ko'],
	},
	KR: {
		name: 'South Korea',
		native: '대한민국',
		phone: [82],
		continent: 'AS',
		capital: 'Seoul',
		currency: ['KRW'],
		languages: ['ko'],
	},
	KW: {
		name: 'Kuwait',
		native: 'الكويت',
		phone: [965],
		continent: 'AS',
		capital: 'Kuwait City',
		currency: ['KWD'],
		languages: ['ara'],
	},
	KY: {
		name: 'Cayman Islands',
		native: 'Cayman Islands',
		phone: [1345],
		continent: 'NA',
		capital: 'George Town',
		currency: ['KYD'],
		languages: ['eng'],
	},
	KZ: {
		name: 'Kazakhstan',
		native: 'Қазақстан',
		phone: [76, 77],
		continent: 'AS',
		continents: ['AS', 'EU'],
		capital: 'Astana',
		currency: ['KZT'],
		languages: ['kk', 'rus'],
	},
	LA: {
		name: 'Laos',
		native: 'ສປປລາວ',
		phone: [856],
		continent: 'AS',
		capital: 'Vientiane',
		currency: ['LAK'],
		languages: ['lao'],
	},
	LB: {
		name: 'Lebanon',
		native: 'لبنان',
		phone: [961],
		continent: 'AS',
		capital: 'Beirut',
		currency: ['LBP'],
		languages: ['ara', 'fre'],
	},
	LC: {
		name: 'Saint Lucia',
		native: 'Saint Lucia',
		phone: [1758],
		continent: 'NA',
		capital: 'Castries',
		currency: ['XCD'],
		languages: ['eng'],
	},
	LI: {
		name: 'Liechtenstein',
		native: 'Liechtenstein',
		phone: [423],
		continent: 'EU',
		capital: 'Vaduz',
		currency: ['CHF'],
		languages: ['deu'],
	},
	LK: {
		name: 'Sri Lanka',
		native: 'śrī laṃkāva',
		phone: [94],
		continent: 'AS',
		capital: 'Colombo',
		currency: ['LKR'],
		languages: ['sin', 'tam'],
	},
	LR: {
		name: 'Liberia',
		native: 'Liberia',
		phone: [231],
		continent: 'AF',
		capital: 'Monrovia',
		currency: ['LRD'],
		languages: ['eng'],
	},
	LS: {
		name: 'Lesotho',
		native: 'Lesotho',
		phone: [266],
		continent: 'AF',
		capital: 'Maseru',
		currency: ['LSL', 'ZAR'],
		languages: ['eng', 'sot'],
	},
	LT: {
		name: 'Lithuania',
		native: 'Lietuva',
		phone: [370],
		continent: 'EU',
		capital: 'Vilnius',
		currency: ['EUR'],
		languages: ['lit'],
	},
	LU: {
		name: 'Luxembourg',
		native: 'Luxembourg',
		phone: [352],
		continent: 'EU',
		capital: 'Luxembourg',
		currency: ['EUR'],
		languages: ['fre', 'deu', 'lux'],
	},
	LV: {
		name: 'Latvia',
		native: 'Latvija',
		phone: [371],
		continent: 'EU',
		capital: 'Riga',
		currency: ['EUR'],
		languages: ['lv'],
	},
	LY: {
		name: 'Libya',
		native: '\u200fليبيا',
		phone: [218],
		continent: 'AF',
		capital: 'Tripoli',
		currency: ['LYD'],
		languages: ['ara'],
	},
	MA: {
		name: 'Morocco',
		native: 'المغرب',
		phone: [212],
		continent: 'AF',
		capital: 'Rabat',
		currency: ['MAD'],
		languages: ['ara'],
	},
	MC: {
		name: 'Monaco',
		native: 'Monaco',
		phone: [377],
		continent: 'EU',
		capital: 'Monaco',
		currency: ['EUR'],
		languages: ['fre'],
	},
	MD: {
		name: 'Moldova',
		native: 'Moldova',
		phone: [373],
		continent: 'EU',
		capital: 'Chișinău',
		currency: ['MDL'],
		languages: ['ron'],
	},
	ME: {
		name: 'Montenegro',
		native: 'Црна Гора',
		phone: [382],
		continent: 'EU',
		capital: 'Podgorica',
		currency: ['EUR'],
		languages: ['srp', 'bos', 'sqi', 'hrv'],
	},
	MF: {
		name: 'Saint Martin',
		native: 'Saint-Martin',
		phone: [590],
		continent: 'NA',
		capital: 'Marigot',
		currency: ['EUR'],
		languages: ['eng', 'fre', 'nld'],
	},
	MG: {
		name: 'Madagascar',
		native: 'Madagasikara',
		phone: [261],
		continent: 'AF',
		capital: 'Antananarivo',
		currency: ['MGA'],
		languages: ['fre', 'mlg'],
	},
	MH: {
		name: 'Marshall Islands',
		native: 'M̧ajeļ',
		phone: [692],
		continent: 'OC',
		capital: 'Majuro',
		currency: ['USD'],
		languages: ['eng', 'mah'],
	},
	MK: {
		name: 'North Macedonia',
		native: 'Северна Македонија',
		phone: [389],
		continent: 'EU',
		capital: 'Skopje',
		currency: ['MKD'],
		languages: ['mkd'],
	},
	ML: {
		name: 'Mali',
		native: 'Mali',
		phone: [223],
		continent: 'AF',
		capital: 'Bamako',
		currency: ['XOF'],
		languages: ['fre'],
	},
	MM: {
		name: 'Myanmar (Burma)',
		native: 'မြန်မာ',
		phone: [95],
		continent: 'AS',
		capital: 'Naypyidaw',
		currency: ['MMK'],
		languages: ['mya'],
	},
	MN: {
		name: 'Mongolia',
		native: 'Монгол улс',
		phone: [976],
		continent: 'AS',
		capital: 'Ulan Bator',
		currency: ['MNT'],
		languages: ['mon'],
	},
	MO: {
		name: 'Macao',
		native: '澳門',
		phone: [853],
		continent: 'AS',
		capital: '',
		currency: ['MOP'],
		languages: ['man', 'por'],
	},
	MP: {
		name: 'Northern Mariana Islands',
		native: 'Northern Mariana Islands',
		phone: [1670],
		continent: 'OC',
		capital: 'Saipan',
		currency: ['USD'],
		languages: ['eng', 'cha'],
	},
	MQ: {
		name: 'Martinique',
		native: 'Martinique',
		phone: [596],
		continent: 'NA',
		capital: 'Fort-de-France',
		currency: ['EUR'],
		languages: ['fre'],
	},
	MR: {
		name: 'Mauritania',
		native: 'موريتانيا',
		phone: [222],
		continent: 'AF',
		capital: 'Nouakchott',
		currency: ['MRU'],
		languages: ['ara'],
	},
	MS: {
		name: 'Montserrat',
		native: 'Montserrat',
		phone: [1664],
		continent: 'NA',
		capital: 'Plymouth',
		currency: ['XCD'],
		languages: ['eng'],
	},
	MT: {
		name: 'Malta',
		native: 'Malta',
		phone: [356],
		continent: 'EU',
		capital: 'Valletta',
		currency: ['EUR'],
		languages: ['mlt', 'eng'],
	},
	MU: {
		name: 'Mauritius',
		native: 'Maurice',
		phone: [230],
		continent: 'AF',
		capital: 'Port Louis',
		currency: ['MUR'],
		languages: ['eng'],
	},
	MV: {
		name: 'Maldives',
		native: 'Maldives',
		phone: [960],
		continent: 'AS',
		capital: 'Malé',
		currency: ['MVR'],
		languages: ['div'],
	},
	MW: {
		name: 'Malawi',
		native: 'Malawi',
		phone: [265],
		continent: 'AF',
		capital: 'Lilongwe',
		currency: ['MWK'],
		languages: ['eng', 'nya'],
	},
	MX: {
		name: 'Mexico',
		native: 'México',
		phone: [52],
		continent: 'NA',
		capital: 'Mexico City',
		currency: ['MXN'],
		languages: ['spa'],
	},
	MY: {
		name: 'Malaysia',
		native: 'Malaysia',
		phone: [60],
		continent: 'AS',
		capital: 'Kuala Lumpur',
		currency: ['MYR'],
		languages: ['msa'],
	},
	MZ: {
		name: 'Mozambique',
		native: 'Moçambique',
		phone: [258],
		continent: 'AF',
		capital: 'Maputo',
		currency: ['MZN'],
		languages: ['por'],
	},
	NA: {
		name: 'Namibia',
		native: 'Namibia',
		phone: [264],
		continent: 'AF',
		capital: 'Windhoek',
		currency: ['NAD', 'ZAR'],
		languages: ['eng', 'afr'],
	},
	NC: {
		name: 'New Caledonia',
		native: 'Nouvelle-Calédonie',
		phone: [687],
		continent: 'OC',
		capital: 'Nouméa',
		currency: ['XPF'],
		languages: ['fre'],
	},
	NE: {
		name: 'Niger',
		native: 'Niger',
		phone: [227],
		continent: 'AF',
		capital: 'Niamey',
		currency: ['XOF'],
		languages: ['fre'],
	},
	NF: {
		name: 'Norfolk Island',
		native: 'Norfolk Island',
		phone: [672],
		continent: 'OC',
		capital: 'Kingston',
		currency: ['AUD'],
		languages: ['eng'],
	},
	NG: {
		name: 'Nigeria',
		native: 'Nigeria',
		phone: [234],
		continent: 'AF',
		capital: 'Abuja',
		currency: ['NGN'],
		languages: ['eng'],
	},
	NI: {
		name: 'Nicaragua',
		native: 'Nicaragua',
		phone: [505],
		continent: 'NA',
		capital: 'Managua',
		currency: ['NIO'],
		languages: ['spa'],
	},
	NL: {
		name: 'Netherlands',
		native: 'Nederland',
		phone: [31],
		continent: 'EU',
		capital: 'Amsterdam',
		currency: ['EUR'],
		languages: ['nld'],
	},
	NO: {
		name: 'Norway',
		native: 'Norge',
		phone: [47],
		continent: 'EU',
		capital: 'Oslo',
		currency: ['NOK'],
		languages: ['nor', 'nob', 'nno'],
	},
	NP: {
		name: 'Nepal',
		native: 'नेपाल',
		phone: [977],
		continent: 'AS',
		capital: 'Kathmandu',
		currency: ['NPR'],
		languages: ['nep'],
	},
	NR: {
		name: 'Nauru',
		native: 'Nauru',
		phone: [674],
		continent: 'OC',
		capital: 'Yaren',
		currency: ['AUD'],
		languages: ['eng', 'nau'],
	},
	NU: {
		name: 'Niue',
		native: 'Niuē',
		phone: [683],
		continent: 'OC',
		capital: 'Alofi',
		currency: ['NZD'],
		languages: ['eng'],
	},
	NZ: {
		name: 'New Zealand',
		native: 'New Zealand',
		phone: [64],
		continent: 'OC',
		capital: 'Wellington',
		currency: ['NZD'],
		languages: ['eng', 'mri'],
	},
	OM: {
		name: 'Oman',
		native: 'عمان',
		phone: [968],
		continent: 'AS',
		capital: 'Muscat',
		currency: ['OMR'],
		languages: ['ara'],
	},
	PA: {
		name: 'Panama',
		native: 'Panamá',
		phone: [507],
		continent: 'NA',
		capital: 'Panama City',
		currency: ['PAB', 'USD'],
		languages: ['spa'],
	},
	PE: {
		name: 'Peru',
		native: 'Perú',
		phone: [51],
		continent: 'SA',
		capital: 'Lima',
		currency: ['PEN'],
		languages: ['spa'],
	},
	PF: {
		name: 'French Polynesia',
		native: 'Polynésie française',
		phone: [689],
		continent: 'OC',
		capital: 'Papeetē',
		currency: ['XPF'],
		languages: ['fre'],
	},
	PG: {
		name: 'Papua New Guinea',
		native: 'Papua Niugini',
		phone: [675],
		continent: 'OC',
		capital: 'Port Moresby',
		currency: ['PGK'],
		languages: ['eng'],
	},
	PH: {
		name: 'Philippines',
		native: 'Pilipinas',
		phone: [63],
		continent: 'AS',
		capital: 'Manila',
		currency: ['PHP'],
		languages: ['eng'],
	},
	PK: {
		name: 'Pakistan',
		native: 'Pakistan',
		phone: [92],
		continent: 'AS',
		capital: 'Islamabad',
		currency: ['PKR'],
		languages: ['eng', 'urd'],
	},
	PL: {
		name: 'Poland',
		native: 'Polska',
		phone: [48],
		continent: 'EU',
		capital: 'Warsaw',
		currency: ['PLN'],
		languages: ['pol'],
	},
	PM: {
		name: 'Saint Pierre and Miquelon',
		native: 'Saint-Pierre-et-Miquelon',
		phone: [508],
		continent: 'NA',
		capital: 'Saint-Pierre',
		currency: ['EUR'],
		languages: ['fre'],
	},
	PN: {
		name: 'Pitcairn Islands',
		native: 'Pitcairn Islands',
		phone: [64],
		continent: 'OC',
		capital: 'Adamstown',
		currency: ['NZD'],
		languages: ['eng'],
	},
	PR: {
		name: 'Puerto Rico',
		native: 'Puerto Rico',
		phone: [1787, 1939],
		continent: 'NA',
		capital: 'San Juan',
		currency: ['USD'],
		languages: ['spa', 'eng'],
	},
	PS: {
		name: 'Palestine',
		native: 'فلسطين',
		phone: [970],
		continent: 'AS',
		capital: 'Ramallah',
		currency: ['ILS'],
		languages: ['ara'],
	},
	PT: {
		name: 'Portugal',
		native: 'Portugal',
		phone: [351],
		continent: 'EU',
		capital: 'Lisbon',
		currency: ['EUR'],
		languages: ['por'],
	},
	PW: {
		name: 'Palau',
		native: 'Palau',
		phone: [680],
		continent: 'OC',
		capital: 'Ngerulmud',
		currency: ['USD'],
		languages: ['eng'],
	},
	PY: {
		name: 'Paraguay',
		native: 'Paraguay',
		phone: [595],
		continent: 'SA',
		capital: 'Asunción',
		currency: ['PYG'],
		languages: ['spa', 'grn'],
	},
	QA: {
		name: 'Qatar',
		native: 'قطر',
		phone: [974],
		continent: 'AS',
		capital: 'Doha',
		currency: ['QAR'],
		languages: ['ara'],
	},
	RE: {
		name: 'Reunion',
		native: 'La Réunion',
		phone: [262],
		continent: 'AF',
		capital: 'Saint-Denis',
		currency: ['EUR'],
		languages: ['fre'],
	},
	RO: {
		name: 'Romania',
		native: 'România',
		phone: [40],
		continent: 'EU',
		capital: 'Bucharest',
		currency: ['RON'],
		languages: ['ron'],
	},
	RS: {
		name: 'Serbia',
		native: 'Србија',
		phone: [381],
		continent: 'EU',
		capital: 'Belgrade',
		currency: ['RSD'],
		languages: ['srp'],
	},
	RU: {
		name: 'Russia',
		native: 'Россия',
		phone: [7],
		continent: 'AS',
		continents: ['AS', 'EU'],
		capital: 'Moscow',
		currency: ['RUB'],
		languages: ['rus'],
	},
	RW: {
		name: 'Rwanda',
		native: 'Rwanda',
		phone: [250],
		continent: 'AF',
		capital: 'Kigali',
		currency: ['RWF'],
		languages: ['kin', 'eng', 'fre'],
	},
	SA: {
		name: 'Saudi Arabia',
		native: 'العربية السعودية',
		phone: [966],
		continent: 'AS',
		capital: 'Riyadh',
		currency: ['SAR'],
		languages: ['ara'],
	},
	SB: {
		name: 'Solomon Islands',
		native: 'Solomon Islands',
		phone: [677],
		continent: 'OC',
		capital: 'Honiara',
		currency: ['SBD'],
		languages: ['eng'],
	},
	SC: {
		name: 'Seychelles',
		native: 'Seychelles',
		phone: [248],
		continent: 'AF',
		capital: 'Victoria',
		currency: ['SCR'],
		languages: ['fre', 'eng'],
	},
	SD: {
		name: 'Sudan',
		native: 'السودان',
		phone: [249],
		continent: 'AF',
		capital: 'Khartoum',
		currency: ['SDG'],
		languages: ['ara', 'eng'],
	},
	SE: {
		name: 'Sweden',
		native: 'Sverige',
		phone: [46],
		continent: 'EU',
		capital: 'Stockholm',
		currency: ['SEK'],
		languages: ['swe'],
	},
	SG: {
		name: 'Singapore',
		native: 'Singapore',
		phone: [65],
		continent: 'AS',
		capital: 'Singapore',
		currency: ['SGD'],
		languages: ['eng', 'msa', 'tam', 'man'],
	},
	SH: {
		name: 'Saint Helena',
		native: 'Saint Helena',
		phone: [290],
		continent: 'AF',
		capital: 'Jamestown',
		currency: ['SHP'],
		languages: ['eng'],
	},
	SI: {
		name: 'Slovenia',
		native: 'Slovenija',
		phone: [386],
		continent: 'EU',
		capital: 'Ljubljana',
		currency: ['EUR'],
		languages: ['slv'],
	},
	SJ: {
		name: 'Svalbard and Jan Mayen',
		native: 'Svalbard og Jan Mayen',
		phone: [4779],
		continent: 'EU',
		capital: 'Longyearbyen',
		currency: ['NOK'],
		languages: ['nor'],
	},
	SK: {
		name: 'Slovakia',
		native: 'Slovensko',
		phone: [421],
		continent: 'EU',
		capital: 'Bratislava',
		currency: ['EUR'],
		languages: ['slk'],
	},
	SL: {
		name: 'Sierra Leone',
		native: 'Sierra Leone',
		phone: [232],
		continent: 'AF',
		capital: 'Freetown',
		currency: ['SLL'],
		languages: ['eng'],
	},
	SM: {
		name: 'San Marino',
		native: 'San Marino',
		phone: [378],
		continent: 'EU',
		capital: 'City of San Marino',
		currency: ['EUR'],
		languages: ['ita'],
	},
	SN: {
		name: 'Senegal',
		native: 'Sénégal',
		phone: [221],
		continent: 'AF',
		capital: 'Dakar',
		currency: ['XOF'],
		languages: ['fre'],
	},
	SO: {
		name: 'Somalia',
		native: 'Soomaaliya',
		phone: [252],
		continent: 'AF',
		capital: 'Mogadishu',
		currency: ['SOS'],
		languages: ['som', 'ara'],
	},
	SR: {
		name: 'Suriname',
		native: 'Suriname',
		phone: [597],
		continent: 'SA',
		capital: 'Paramaribo',
		currency: ['SRD'],
		languages: ['nld'],
	},
	SS: {
		name: 'South Sudan',
		native: 'South Sudan',
		phone: [211],
		continent: 'AF',
		capital: 'Juba',
		currency: ['SSP'],
		languages: ['eng'],
	},
	ST: {
		name: 'Sao Tome and Principe',
		native: 'São Tomé e Príncipe',
		phone: [239],
		continent: 'AF',
		capital: 'São Tomé',
		currency: ['STN'],
		languages: ['por'],
	},
	SV: {
		name: 'El Salvador',
		native: 'El Salvador',
		phone: [503],
		continent: 'NA',
		capital: 'San Salvador',
		currency: ['SVC', 'USD'],
		languages: ['spa'],
	},
	SX: {
		name: 'Sint Maarten',
		native: 'Sint Maarten',
		phone: [1721],
		continent: 'NA',
		capital: 'Philipsburg',
		currency: ['ANG'],
		languages: ['nld', 'eng'],
	},
	SY: {
		name: 'Syria',
		native: 'سوريا',
		phone: [963],
		continent: 'AS',
		capital: 'Damascus',
		currency: ['SYP'],
		languages: ['ara'],
	},
	SZ: {
		name: 'Eswatini',
		native: 'Eswatini',
		phone: [268],
		continent: 'AF',
		capital: 'Lobamba',
		currency: ['SZL'],
		languages: ['eng', 'ssw'],
	},
	TC: {
		name: 'Turks and Caicos Islands',
		native: 'Turks and Caicos Islands',
		phone: [1649],
		continent: 'NA',
		capital: 'Cockburn Town',
		currency: ['USD'],
		languages: ['eng'],
	},
	TD: {
		name: 'Chad',
		native: 'Tchad',
		phone: [235],
		continent: 'AF',
		capital: "N'Djamena",
		currency: ['XAF'],
		languages: ['fre', 'ara'],
	},
	TF: {
		name: 'French Southern Territories',
		native: 'Territoire des Terres australes et antarctiques fr',
		phone: [262],
		continent: 'AN',
		capital: 'Port-aux-Français',
		currency: ['EUR'],
		languages: ['fre'],
	},
	TG: {
		name: 'Togo',
		native: 'Togo',
		phone: [228],
		continent: 'AF',
		capital: 'Lomé',
		currency: ['XOF'],
		languages: ['fre'],
	},
	TH: {
		name: 'Thailand',
		native: 'ประเทศไทย',
		phone: [66],
		continent: 'AS',
		capital: 'Bangkok',
		currency: ['THB'],
		languages: ['tha'],
	},
	TJ: {
		name: 'Tajikistan',
		native: 'Тоҷикистон',
		phone: [992],
		continent: 'AS',
		capital: 'Dushanbe',
		currency: ['TJS'],
		languages: ['tgk', 'rus'],
	},
	TK: {
		name: 'Tokelau',
		native: 'Tokelau',
		phone: [690],
		continent: 'OC',
		capital: 'Fakaofo',
		currency: ['NZD'],
		languages: ['eng'],
	},
	TL: {
		name: 'East Timor',
		native: 'Timor-Leste',
		phone: [670],
		continent: 'OC',
		capital: 'Dili',
		currency: ['USD'],
		languages: ['por'],
	},
	TM: {
		name: 'Turkmenistan',
		native: 'Türkmenistan',
		phone: [993],
		continent: 'AS',
		capital: 'Ashgabat',
		currency: ['TMT'],
		languages: ['tuk', 'rus'],
	},
	TN: {
		name: 'Tunisia',
		native: 'تونس',
		phone: [216],
		continent: 'AF',
		capital: 'Tunis',
		currency: ['TND'],
		languages: ['ara'],
	},
	TO: {
		name: 'Tonga',
		native: 'Tonga',
		phone: [676],
		continent: 'OC',
		capital: "Nuku'alofa",
		currency: ['TOP'],
		languages: ['eng', 'ton'],
	},
	TR: {
		name: 'Turkey',
		native: 'Türkiye',
		phone: [90],
		continent: 'AS',
		continents: ['AS', 'EU'],
		capital: 'Ankara',
		currency: ['TRY'],
		languages: ['tur'],
	},
	TT: {
		name: 'Trinidad and Tobago',
		native: 'Trinidad and Tobago',
		phone: [1868],
		continent: 'NA',
		capital: 'Port of Spain',
		currency: ['TTD'],
		languages: ['eng'],
	},
	TV: {
		name: 'Tuvalu',
		native: 'Tuvalu',
		phone: [688],
		continent: 'OC',
		capital: 'Funafuti',
		currency: ['AUD'],
		languages: ['eng'],
	},
	TW: {
		name: 'Taiwan',
		native: '臺灣',
		phone: [886],
		continent: 'AS',
		capital: 'Taipei',
		currency: ['TWD'],
		languages: ['taw'],
	},
	TZ: {
		name: 'Tanzania',
		native: 'Tanzania',
		phone: [255],
		continent: 'AF',
		capital: 'Dodoma',
		currency: ['TZS'],
		languages: ['swa', 'eng'],
	},
	UA: {
		name: 'Ukraine',
		native: 'Україна',
		phone: [380],
		continent: 'EU',
		capital: 'Kyiv',
		currency: ['UAH'],
		languages: ['ukr'],
	},
	UG: {
		name: 'Uganda',
		native: 'Uganda',
		phone: [256],
		continent: 'AF',
		capital: 'Kampala',
		currency: ['UGX'],
		languages: ['eng', 'swa'],
	},
	UM: {
		name: 'U.S. Minor Outlying Islands',
		native: 'United States Minor Outlying Islands',
		phone: [1],
		continent: 'OC',
		capital: '',
		currency: ['USD'],
		languages: ['eng'],
	},
	US: {
		name: 'United States',
		native: 'United States',
		phone: [1],
		continent: 'NA',
		capital: 'Washington D.C.',
		currency: ['USD', 'USN', 'USS'],
		languages: ['eng'],
	},
	UY: {
		name: 'Uruguay',
		native: 'Uruguay',
		phone: [598],
		continent: 'SA',
		capital: 'Montevideo',
		currency: ['UYI', 'UYU'],
		languages: ['spa'],
	},
	UZ: {
		name: 'Uzbekistan',
		native: "O'zbekiston",
		phone: [998],
		continent: 'AS',
		capital: 'Tashkent',
		currency: ['UZS'],
		languages: ['uzb', 'rus'],
	},
	VA: {
		name: 'Vatican City',
		native: 'Vaticano',
		phone: [379],
		continent: 'EU',
		capital: 'Vatican City',
		currency: ['EUR'],
		languages: ['ita', 'lat'],
	},
	VC: {
		name: 'Saint Vincent and the Grenadines',
		native: 'Saint Vincent and the Grenadines',
		phone: [1784],
		continent: 'NA',
		capital: 'Kingstown',
		currency: ['XCD'],
		languages: ['eng'],
	},
	VE: {
		name: 'Venezuela',
		native: 'Venezuela',
		phone: [58],
		continent: 'SA',
		capital: 'Caracas',
		currency: ['VES'],
		languages: ['spa'],
	},
	VG: {
		name: 'British Virgin Islands',
		native: 'British Virgin Islands',
		phone: [1284],
		continent: 'NA',
		capital: 'Road Town',
		currency: ['USD'],
		languages: ['eng'],
	},
	VI: {
		name: 'U.S. Virgin Islands',
		native: 'United States Virgin Islands',
		phone: [1340],
		continent: 'NA',
		capital: 'Charlotte Amalie',
		currency: ['USD'],
		languages: ['eng'],
	},
	VN: {
		name: 'Vietnam',
		native: 'Việt Nam',
		phone: [84],
		continent: 'AS',
		capital: 'Hanoi',
		currency: ['VND'],
		languages: ['vie'],
	},
	VU: {
		name: 'Vanuatu',
		native: 'Vanuatu',
		phone: [678],
		continent: 'OC',
		capital: 'Port Vila',
		currency: ['VUV'],
		languages: ['bis', 'eng', 'fre'],
	},
	WF: {
		name: 'Wallis and Futuna',
		native: 'Wallis et Futuna',
		phone: [681],
		continent: 'OC',
		capital: 'Mata-Utu',
		currency: ['XPF'],
		languages: ['fre'],
	},
	WS: {
		name: 'Samoa',
		native: 'Samoa',
		phone: [685],
		continent: 'OC',
		capital: 'Apia',
		currency: ['WST'],
		languages: ['smo', 'eng'],
	},
	XK: {
		name: 'Kosovo',
		native: 'Republika e Kosovës',
		phone: [377, 381, 383, 386],
		continent: 'EU',
		capital: 'Pristina',
		currency: ['EUR'],
		languages: ['sqi', 'srp'],
	},
	YE: {
		name: 'Yemen',
		native: 'اليَمَن',
		phone: [967],
		continent: 'AS',
		capital: "Sana'a",
		currency: ['YER'],
		languages: ['ara'],
	},
	YT: {
		name: 'Mayotte',
		native: 'Mayotte',
		phone: [262],
		continent: 'AF',
		capital: 'Mamoudzou',
		currency: ['EUR'],
		languages: ['fre'],
	},
	ZA: {
		name: 'South Africa',
		native: 'South Africa',
		phone: [27],
		continent: 'AF',
		capital: 'Pretoria',
		currency: ['ZAR'],
		languages: [
			'afr',
			'eng',
			'nbl',
			'sot',
			'ssw',
			'tsn',
			'tso',
			'ven',
			'xho',
			'zul',
		],
	},
	ZM: {
		name: 'Zambia',
		native: 'Zambia',
		phone: [260],
		continent: 'AF',
		capital: 'Lusaka',
		currency: ['ZMW'],
		languages: ['eng'],
	},
	ZW: {
		name: 'Zimbabwe',
		native: 'Zimbabwe',
		phone: [263],
		continent: 'AF',
		capital: 'Harare',
		currency: ['USD', 'ZAR', 'BWP', 'GBP', 'AUD', 'CNY', 'INR', 'JPY'],
		languages: ['eng', 'sna', 'nde'],
	},
};
